[package]
name = "smartchatai"
version = "0.2.0"
edition = "2021"
description = "Smartchatai as a native terminal executable"

[[bin]]
name = "smartchatai"
path = "src/main.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"
